### ISSUE TITLE
Map taxonomy of C-CAT Collateral Consequences Tool

### ISSUE THREAD

**Issue by ejaxon** [CodeForNC/nc-reentry-resources-content#3]
The [Collateral Consequences Tool](https://ccat.sog.unc.edu/) documents the impact of various felony convictions on eligibility for jobs, benefits and educational assistance. It is developed by the UNC School of Government.

The team behind the tool is interested in working with us both to improve their tool and to enable us to integrate useful information from the tool into the Reentry Hub.

The goal of this task is to map out the taxonomy of the information and how it maps to individual pages. For example, [https://ccat.sog.unc.edu/search/211](https://ccat.sog.unc.edu/search/211) corresponds to the Housing/Eviction consequence category. 

Ideally we would like to put links from the reentry hub directly to the relevant pages in the C-CAT (e.g., we might list eviction on the housing page and link directly to the page above). To do this, we need a good map of the site's content, which brief descriptions of the kind of information available at each link.

**Comment by tracyavl** [comment]
I think the most direct way to do this would be to just go through the topic pages in the site and link where there is one. For example, Housing
On second bullet point “your specific criminal history can impact the type of housing that is available to you” add, “Find out more on C-CAT.”  and link to the search you mention above. Now that I understand this task, I'll try to put some time to it Saturday.

**Comment by ejaxon** [comment]
Perfect. I'll reach out to the folks at School of Government this week and see if we can just get the taxonomy from them.

BTW they are interested in improving the usability of C-CAT. That mostly involves getting actual users of the site, but any thoughts you have would be great. They don't have a lot of development resources, but we've talked and I believe there are some reasonable improvements that could be made essentially by overlaying a simpler interface. That's partly what we're doing.
