### ISSUE TITLE
Usability testing of existing site

### ISSUE THREAD

**Issue by ejaxon** [CodeForNC/nc-reentry-resources-content#5]
The current [Buncombe Reentry Resources Hub](http://www.buncombereentryhub.org/) was our first iteration. Before we convert that content over and finish implementation of the new site, we need to better understand what works or doesn't work well there in terms of:

- Navigation
- Readability
- Organization

**Comment by tracyavl** [comment]
David and I are working on usability/feedback on the new site, which also includes parts of the old page. We will post our feedback in a google doc which we'll upload

**Comment by ChrisTheDBA** [comment]
We have three testing in G'boro. Creating a grid of browsers and OS in google doc. we'll add back.

**Comment by gitvance** [comment]
I (Vance) can add my feedback to the Google Doc mentioned above.  I'll check for usability on a MacBook running OS X (Yosemite 10.10.5), a Samsung phone (Android 5.1.1), and a 2nd-generation iPad.  The browsers will be Mozilla Firefox, Chrome, and Safari.

**Comment by ChrisTheDBA** [comment]
Here is the link to the google doc on compatibility matrix -https://docs.google.com/document/d/1ZtXLSmiAfHD9VpkuoCTxBjyZsunxRQNcCIlyyO0A9u8/edit?usp=sharing

**Comment by tracyavl** [comment]
Here is the link to the doc outlining plans for home page and structure to give context to all the resources, plus some general feedback on a little of the site - although we didn't get all the way through it. There are other new pages suggested in there to give context and guidance to anyone using the site.

https://docs.google.com/document/d/1Q9R-HuCXTifabaaGyya_RJORC025An2d4yXqHYPI_Kk/edit?usp=sharing

**Comment by ejaxon** [comment]
Thanks for this, everyone!

**Comment by ejaxon** [comment]
@tracyavl, @ChrisTheDBA Sorry for delay getting to this - I spent the last couple weeks on a bit of a health adventure. All fine, but comeback has been a little slow.

@tracyavl Finally read through the doc - great stuff! I need to sync up with @marshallj to think through how this impacts content & code architecture (I think it's minor, but want to talk through), but I really like the idea of deliberately targeting specific user groups and guiding them appropriately.

More on this soon.

**Comment by ejaxon** [comment]
Also @ChrisTheDBA was the plan to add feedback to the compatibility matrix or just create issues? I saw the one re: iphone from @pokespeon, but didn't see any others. Maybe it was a bit early to test that?

**Comment by ChrisTheDBA** [comment]
I wanted to get out there what we testing on. With the site being
re-designed we probably need to step back and wait.

Chris Mathews
