### ISSUE TITLE
need more local homes for rent

### ISSUE THREAD

**Issue by pokespeon** [CodeForNC/nc-reentry-resources-content#9]
there is only 3

**Comment by pokespeon** [comment]
maybe allow user to search around them by using their current location

**Comment by ChrisTheDBA** [comment]
Would access to zillow be useful? API for home search?

**Comment by ejaxon** [comment]
Thanks, @pokespeon. I think we're mostly not going to try to be a direct resource for finding housing, but rather will list places people can go to get assistance finding. I'm going to close a couple of the other issues you opened on this topic for the same reason.
